import {useEffect,useMemo,useState} from 'react'
import {Modal,Pressable,ScrollView,Text,View} from 'react-native'
import type {Category,Equipment,Exercise,MuscleGroup} from '../domain/models'
import {filterExercises,type ExerciseFilters,type ExerciseOrigin} from '../domain/catalog'
import {loadCatalogPreferences,rememberRecent,toggleFavorite} from '../state/catalogPreferences'
import {Button,Card,Empty,Input,styles} from './components'
import {colors} from './theme'

const muscles:(MuscleGroup|null)[]=[null,'chest','back','legs','shoulders','biceps','triceps','core','glutes','calves','forearms']
const equipment:(Equipment|null)[]=[null,'barbell','dumbbell','machine','cable','bodyweight','kettlebell','band']
const categories:(Category|null)[]=[null,'compound','isolation'],origins:ExerciseOrigin[]=['all','default','custom']
const labels:Record<string,string>={chest:'Peito',back:'Costas',legs:'Pernas',shoulders:'Ombros',biceps:'Bíceps',triceps:'Tríceps',core:'Core',glutes:'Glúteos',calves:'Panturrilhas',forearms:'Antebraços',barbell:'Barra',dumbbell:'Halteres',machine:'Máquina',cable:'Polia',bodyweight:'Peso corporal',kettlebell:'Kettlebell',band:'Elástico',compound:'Composto',isolation:'Isolador',all:'Todas as origens',default:'Padrão',custom:'Personalizado'}
function Cycle<T extends string>({title,value,values,onChange}:{title:string;value:T|null;values:(T|null)[];onChange:(x:T|null)=>void}){const current=values.indexOf(value);return <Pressable accessibilityRole="button" onPress={()=>onChange(values[(current+1)%values.length])} style={{backgroundColor:colors.card2,borderColor:colors.line,borderWidth:1,padding:10,borderRadius:9}}><Text style={styles.muted}>{title}</Text><Text style={styles.body}>{value?labels[value]??value:'Todos'}</Text></Pressable>}
export function ExercisePicker({visible,exercises,vaultUri,onClose,onPick}:{visible:boolean;exercises:Exercise[];vaultUri:string;onClose:()=>void;onPick:(exercise:Exercise)=>void}){const [filters,setFilters]=useState<ExerciseFilters>({query:'',muscle:null,equipment:null,category:null,origin:'all'}),[favorites,setFavorites]=useState<string[]>([]),[recent,setRecent]=useState<string[]>([]);useEffect(()=>{if(visible)loadCatalogPreferences(vaultUri).then(x=>{setFavorites(x.favorites);setRecent(x.recent)})},[visible,vaultUri]);const found=useMemo(()=>filterExercises(exercises,filters),[exercises,filters]),ranked=useMemo(()=>[...found].sort((a,b)=>{const section=(x:Exercise)=>favorites.includes(x.id)?0:recent.includes(x.id)?1:2;return section(a)-section(b)||a.name.localeCompare(b.name,'pt-BR')}),[found,favorites,recent]);const pick=async(x:Exercise)=>{setRecent(await rememberRecent(vaultUri,x.id));onPick(x)};return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><View style={styles.screen}><View style={styles.row}><Text style={{...styles.title,flex:1,fontSize:22}}>Adicionar exercício</Text><Button title="Fechar" secondary onPress={onClose}/></View><Input autoFocus placeholder="Buscar por nome ou descrição…" value={filters.query} onChangeText={query=>setFilters(x=>({...x,query}))}/><View style={{flexDirection:'row',flexWrap:'wrap',gap:7}}><Cycle title="Grupo" value={filters.muscle} values={muscles} onChange={muscle=>setFilters(x=>({...x,muscle}))}/><Cycle title="Equipamento" value={filters.equipment} values={equipment} onChange={equipment=>setFilters(x=>({...x,equipment}))}/><Cycle title="Categoria" value={filters.category} values={categories} onChange={category=>setFilters(x=>({...x,category}))}/><Cycle title="Origem" value={filters.origin} values={origins} onChange={origin=>setFilters(x=>({...x,origin:origin!}))}/></View><Text style={styles.muted}>{ranked.length} resultado(s) · ★ favoritos aparecem primeiro · recentes em seguida</Text><ScrollView contentContainerStyle={{gap:8,paddingBottom:30}}>{!ranked.length&&<Empty>Nenhum exercício combina com os filtros.</Empty>}{ranked.map(x=><Card key={x.id}><View style={styles.row}><View style={{flex:1}}><Text style={{...styles.body,fontWeight:'800'}}>{favorites.includes(x.id)?'★ ':recent.includes(x.id)?'◷ ':''}{x.name}</Text><Text style={styles.muted}>{labels[x.primary_muscle_group]} · {labels[x.equipment]} · {x.custom?'Personalizado':'Padrão'}</Text></View><Button title={favorites.includes(x.id)?'★':'☆'} secondary onPress={()=>toggleFavorite(vaultUri,x.id).then(setFavorites)}/></View><Button title="Adicionar" onPress={()=>pick(x)}/></Card>)}</ScrollView></View></Modal>}
