default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV.fetch("DATABASE_URL", "postgres://postgres:postgres@db:5432/lift_that_sh_development") %>

development:
  <<: *default

production:
  <<: *default
