source "https://rubygems.org"

gem "rails", "~> 8.0.0"
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "devise", "~> 4.9"
gem "devise-jwt", "~> 0.12"
gem "rack-cors", "~> 2.0"

group :development do
  gem "debug", require: false
end
